name: Modrinth release
on: 
  push:
    tags:
      - '*'
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
      - name: Create zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Better-Vanilla-Advancements-${{github.ref_name}}.zip src
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Better-Vanilla-Advancements-${{github.ref_name}}.zip
          path: Better-Vanilla-Advancements-${{github.ref_name}}.zip
      - name: Read supported versions
        uses: andstor/file-reader-action@v1
        id: read_file
        with:
          path: src/supported_versions.txt
      - name: Upload to modrinth
        uses: kir-antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{secrets.ACCESS_TOKEN}}
          modrinth-id: 4b7eLx1x
          version: ${{github.ref_name}}
          files: |
            !src/supported_versions.txt
            !src/LICENSE
            !src/README.md
            src/*
          game-versions: ${{steps.read_file.outputs.contents}}
          loaders: datapack
